# Generated by Django 4.2 on 2024-02-13 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=3, unique=True, verbose_name='Буквенный код валюты')),
                ('name_ru', models.CharField(max_length=128, verbose_name='Имя на русском')),
                ('name_eng', models.CharField(max_length=128, verbose_name='Имя на английском')),
                ('scale', models.IntegerField(verbose_name='Количество единиц валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'db_table': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата установки курса')),
                ('rate', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Курс')),
                ('currency_abbreviation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='currencies.currency', to_field='abbreviation', verbose_name='Код валюты')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'rates',
            },
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['abbreviation'], name='currencies_abbrevi_0fe99d_idx'),
        ),
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['date'], name='rates_date_3aa1d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('currency_abbreviation', 'date')},
        ),
    ]
