# Generated by Django 4.2 on 2024-03-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-02-29 18:58:30"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="currency",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="rate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-02-29 18:58:30"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
