from os import getenv as ENV


BOT_TOKEN = ENV("BOT_TOKEN")
WEBHOOK_URL = ENV("WEBHOOK_URL")
PROXY_SERVER = ENV("PROXY_SERVER")
SECRET_TOKEN = ENV("SECRET_TOKEN")
BOT_PORT = ENV("BOT_PORT")
BOT_HOST = ENV("BOT_HOST")