name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: main
    
      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE }}
          script: |
            cd /home/code
            git pull