name: Integration
on:
  workflow_run:
    workflows: ["Deploy"]
    branches: [main]
    types: 
      - completed

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE }}
          script: |
            cd /home/code
            docker compose --env-file .env up --build -d
            
